export interface Movie {
  id: string;
  title: string;
  posterUrl: string;
  year: number;
  isFeatured: boolean;
  genre: string;
  quality?: string;
  tags?: string[];
}

export const featuredMovies: Movie[] = [
  {
    id: '1',
    title: 'Chrono Rift',
    posterUrl: 'https://placehold.co/400x600.png',
    year: 2024,
    isFeatured: true,
    genre: 'Sci-Fi, Action',
    quality: '4K',
    tags: ['Featured', 'New'],
  },
  {
    id: '2',
    title: 'Neon Dystopia',
    posterUrl: 'https://placehold.co/400x602.png',
    year: 2024,
    isFeatured: true,
    genre: 'Cyberpunk, Thriller',
    quality: 'HD',
    tags: ['Featured'],
  },
  {
    id: '3',
    title: 'The Crimson Cipher',
    posterUrl: 'https://placehold.co/400x604.png',
    year: 2024,
    isFeatured: true,
    genre: 'Mystery, Crime',
    quality: '4K',
    tags: ['Featured'],
  },
  {
    id: '4',
    title: 'Galaxy\'s Edge',
    posterUrl: 'https://placehold.co/400x606.png',
    year: 2024,
    isFeatured: true,
    genre: 'Space Opera, Adventure',
    quality: 'HD',
    tags: ['Featured'],
  },
    {
    id: '5',
    title: 'Ocean\'s Whisper',
    posterUrl: 'https://placehold.co/400x608.png',
    year: 2023,
    isFeatured: true,
    genre: 'Drama, Romance',
    quality: '4K',
    tags: ['Featured'],
  },
];

export const latestReleases: Movie[] = [
  {
    id: '6',
    title: 'Forgotten Echoes',
    posterUrl: 'https://placehold.co/400x599.png',
    year: 2024,
    isFeatured: false,
    genre: 'Horror, Thriller',
    quality: 'HD',
    tags: ['New Release'],
  },
  {
    id: '7',
    title: 'The Alchemist\'s Heir',
    posterUrl: 'https://placehold.co/400x601.png',
    year: 2024,
    isFeatured: false,
    genre: 'Fantasy, Adventure',
    quality: '4K',
    tags: ['New Release'],
  },
  {
    id: '8',
    title: 'Zero Protocol',
    posterUrl: 'https://placehold.co/400x603.png',
    year: 2024,
    isFeatured: false,
    genre: 'Action, Espionage',
    quality: 'HD',
    tags: ['New Release'],
  },
  {
    id: '9',
    title: 'Concrete Jungle',
    posterUrl: 'https://placehold.co/400x605.png',
    year: 2024,
    isFeatured: false,
    genre: 'Action, Crime',
    quality: '4K',
    tags: ['New Release'],
  },
  {
    id: '10',
    title: 'Summer Bloom',
    posterUrl: 'https://placehold.co/400x607.png',
    year: 2024,
    isFeatured: false,
    genre: 'Comedy, Romance',
    quality: 'HD',
    tags: ['New Release'],
  },
  {
    id: '11',
    title: 'Path of the Ronin',
    posterUrl: 'https://placehold.co/400x609.png',
    year: 2024,
    isFeatured: false,
    genre: 'Historical, Action',
    quality: '4K',
    tags: ['New Release'],
  },
   {
    id: '12',
    title: 'Helios',
    posterUrl: 'https://placehold.co/400x610.png',
    year: 2024,
    isFeatured: false,
    genre: 'Sci-Fi',
    quality: 'HD',
    tags: ['New Release'],
  },
  {
    id: '13',
    title: 'Quantum Entanglement',
    posterUrl: 'https://placehold.co/400x611.png',
    year: 2024,
    isFeatured: false,
    genre: 'Sci-Fi, Romance',
    quality: '4K',
    tags: ['New Release'],
  },
  {
    id: '14',
    title: 'Midnight Sun',
    posterUrl: 'https://placehold.co/400x612.png',
    year: 2024,
    isFeatured: false,
    genre: 'Vampire, Romance',
    quality: 'HD',
    tags: ['New Release'],
  },
  {
    id: '15',
    title: 'The Last Stand',
    posterUrl: 'https://placehold.co/400x613.png',
    year: 2024,
    isFeatured: false,
    genre: 'Action, Western',
    quality: '4K',
    tags: ['New Release'],
  },
  {
    id: '16',
    title: 'Project Chimera',
    posterUrl: 'https://placehold.co/400x614.png',
    year: 2024,
    isFeatured: false,
    genre: 'Sci-Fi, Horror',
    quality: 'HD',
    tags: ['New Release'],
  },
  {
    id: '17',
    title: 'The Gilded Cage',
    posterUrl: 'https://placehold.co/400x615.png',
    year: 2024,
    isFeatured: false,
    genre: 'Drama, Historical',
    quality: '4K',
    tags: ['New Release'],
  },
];
