
export interface Movie {
  id: string;
  title: string;
  posterUrl: string;
  year: number;
  isFeatured: boolean;
  genre: string;
  quality?: string;
  tags?: string[];
}

export const featuredMovies: Movie[] = [
  {
    id: '1',
    title: 'Inception',
    posterUrl: 'https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq27gApcjBveAabcF.jpg',
    year: 2010,
    isFeatured: true,
    genre: 'Sci-Fi, Action',
    quality: '4K',
    tags: ['Featured', 'Mind-bending'],
  },
  {
    id: '2',
    title: 'The Dark Knight',
    posterUrl: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    year: 2008,
    isFeatured: true,
    genre: 'Action, Crime, Drama',
    quality: 'HD',
    tags: ['Featured', 'Superhero'],
  },
  {
    id: '3',
    title: 'Interstellar',
    posterUrl: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    year: 2014,
    isFeatured: true,
    genre: 'Adventure, Drama, Sci-Fi',
    quality: '4K',
    tags: ['Featured', 'Space'],
  },
  {
    id: '4',
    title: 'Parasite',
    posterUrl: 'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
    year: 2019,
    isFeatured: true,
    genre: 'Comedy, Drama, Thriller',
    quality: 'HD',
    tags: ['Featured', 'Award-winning'],
  },
  {
    id: '5',
    title: 'Joker',
    posterUrl: 'https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg',
    year: 2019,
    isFeatured: true,
    genre: 'Crime, Drama, Thriller',
    quality: '4K',
    tags: ['Featured', 'Psychological'],
  },
  {
    id: '6',
    title: 'Dune',
    posterUrl: 'https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIY2VhrhXLon3fCn.jpg',
    year: 2021,
    isFeatured: true,
    genre: 'Sci-Fi, Adventure',
    quality: 'HD',
    tags: ['Featured', 'Epic'],
  },
  {
    id: '7',
    title: 'Spider-Man: No Way Home',
    posterUrl: 'https://image.tmdb.org/t/p/w500/1g0dhYtq4irDe3GPvareA-M0mp.jpg',
    year: 2021,
    isFeatured: true,
    genre: 'Action, Adventure, Sci-Fi',
    quality: '4K',
    tags: ['Featured', 'Marvel'],
  },
  {
    id: '8',
    title: 'The Matrix',
    posterUrl: 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9Gz0gSbn0QZfo.jpg',
    year: 1999,
    isFeatured: true,
    genre: 'Action, Sci-Fi',
    quality: 'HD',
    tags: ['Featured', 'Classic'],
  },
  {
    id: '9',
    title: 'Forrest Gump',
    posterUrl: 'https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
    year: 1994,
    isFeatured: true,
    genre: 'Comedy, Drama, Romance',
    quality: '4K',
    tags: ['Featured', 'Heartwarming'],
  },
  {
    id: '10',
    title: 'Pulp Fiction',
    posterUrl: 'https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
    year: 1994,
    isFeatured: true,
    genre: 'Crime, Drama',
    quality: 'HD',
    tags: ['Featured', 'Iconic'],
  },
];

export const latestReleases: Movie[] = [
  {
    id: '11',
    title: 'Oppenheimer',
    posterUrl: 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    year: 2023,
    isFeatured: false,
    genre: 'Biography, Drama, History',
    quality: '4K',
    tags: ['New Release'],
  },
  {
    id: '12',
    title: 'Barbie',
    posterUrl: 'https://image.tmdb.org/t/p/w500/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg',
    year: 2023,
    isFeatured: false,
    genre: 'Comedy, Adventure, Fantasy',
    quality: 'HD',
    tags: ['New Release'],
  },
  {
    id: '13',
    title: 'Everything Everywhere All at Once',
    posterUrl: 'https://image.tmdb.org/t/p/w500/w3LxiVYUpllpCmst2stCDsqeRJt.jpg',
    year: 2022,
    isFeatured: false,
    genre: 'Action, Adventure, Sci-Fi',
    quality: '4K',
    tags: ['New Release'],
  },
  {
    id: '14',
    title: 'The Batman',
    posterUrl: 'https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg',
    year: 2022,
    isFeatured: false,
    genre: 'Action, Crime, Drama',
    quality: 'HD',
    tags: ['New Release'],
  },
  {
    id: '15',
    title: 'Top Gun: Maverick',
    posterUrl: 'https://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DX17ljH.jpg',
    year: 2022,
    isFeatured: false,
    genre: 'Action, Drama',
    quality: '4K',
    tags: ['New Release'],
  },
  {
    id: '16',
    title: 'Avatar: The Way of Water',
    posterUrl: 'https://image.tmdb.org/t/p/w500/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg',
    year: 2022,
    isFeatured: false,
    genre: 'Sci-Fi, Adventure, Action',
    quality: 'HD',
    tags: ['New Release'],
  },
   {
    id: '17',
    title: 'Knives Out',
    posterUrl: 'https://image.tmdb.org/t/p/w500/6H2DNJOI4Ikmh1xQe4pG6K2iH22.jpg',
    year: 2019,
    isFeatured: false,
    genre: 'Comedy, Crime, Mystery',
    quality: 'HD',
    tags: ['Popular'],
  },
  {
    id: '18',
    title: 'Get Out',
    posterUrl: 'https://image.tmdb.org/t/p/w500/1swD0je224w0aP4iJd2NPh6voax.jpg',
    year: 2017,
    isFeatured: false,
    genre: 'Horror, Mystery, Thriller',
    quality: '4K',
    tags: ['Critically Acclaimed'],
  },
  {
    id: '19',
    title: 'Mad Max: Fury Road',
    posterUrl: 'https://image.tmdb.org/t/p/w500/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg',
    year: 2015,
    isFeatured: false,
    genre: 'Action, Adventure, Sci-Fi',
    quality: 'HD',
    tags: ['Adrenaline Rush'],
  },
  {
    id: '20',
    title: 'The Social Network',
    posterUrl: 'https://image.tmdb.org/t/p/w500/n0ybibhJtQ5icDqNs2BT90gBfgM.jpg',
    year: 2010,
    isFeatured: false,
    genre: 'Drama, History',
    quality: '4K',
    tags: ['Biography'],
  },
  {
    id: '21',
    title: 'Whiplash',
    posterUrl: 'https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg',
    year: 2014,
    isFeatured: false,
    genre: 'Drama, Music',
    quality: 'HD',
    tags: ['Intense'],
  },
  {
    id: '22',
    title: 'Blade Runner 2049',
    posterUrl: 'https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg',
    year: 2017,
    isFeatured: false,
    genre: 'Sci-Fi, Thriller',
    quality: '4K',
    tags: ['Visually Stunning'],
  },
];
