
export interface Movie {
  id: string;
  title: string;
  posterUrl: string;
  year: number;
  isFeatured: boolean;
  genre: string;
  quality?: string;
  tags?: string[];
}

// This data is now used for initial database seeding.
export const initialFeaturedMovies: Movie[] = [
  {
    id: '1',
    title: 'Inception',
    posterUrl: 'https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq27gApcjBveAabcF.jpg',
    year: 2010,
    isFeatured: true,
    genre: 'Sci-Fi, Action',
    quality: '4K',
    tags: ['Featured', 'Mind-bending'],
  },
  {
    id: '2',
    title: 'The Dark Knight',
    posterUrl: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    year: 2008,
    isFeatured: true,
    genre: 'Action, Crime, Drama',
    quality: 'HD',
    tags: ['Featured', 'Superhero'],
  },
  {
    id: '3',
    title: 'Interstellar',
    posterUrl: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    year: 2014,
    isFeatured: true,
    genre: 'Adventure, Drama, Sci-Fi',
    quality: '4K',
    tags: ['Featured', 'Space'],
  },
  {
    id: '4',
    title: 'Parasite',
    posterUrl: 'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
    year: 2019,
    isFeatured: true,
    genre: 'Comedy, Drama, Thriller',
    quality: 'HD',
    tags: ['Featured', 'Award-winning'],
  },
  {
    id: '5',
    title: 'Joker',
    posterUrl: 'https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg',
    year: 2019,
    isFeatured: true,
    genre: 'Crime, Drama, Thriller',
    quality: '4K',
    tags: ['Featured', 'Psychological'],
  },
  {
    id: '6',
    title: 'Dune',
    posterUrl: 'https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIY2VhrhXLon3fCn.jpg',
    year: 2021,
    isFeatured: true,
    genre: 'Sci-Fi, Adventure',
    quality: 'HD',
    tags: ['Featured', 'Epic'],
  },
  {
    id: '7',
    title: 'Spider-Man: No Way Home',
    posterUrl: 'https://image.tmdb.org/t/p/w500/1g0dhYtq4irDe3GPvareA-M0mp.jpg',
    year: 2021,
    isFeatured: true,
    genre: 'Action, Adventure, Sci-Fi',
    quality: '4K',
    tags: ['Featured', 'Marvel'],
  },
  {
    id: '8',
    title: 'The Matrix',
    posterUrl: 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9Gz0gSbn0QZfo.jpg',
    year: 1999,
    isFeatured: true,
    genre: 'Action, Sci-Fi',
    quality: 'HD',
    tags: ['Featured', 'Classic'],
  },
  {
    id: '9',
    title: 'Forrest Gump',
    posterUrl: 'https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
    year: 1994,
    isFeatured: true,
    genre: 'Comedy, Drama, Romance',
    quality: '4K',
    tags: ['Featured', 'Heartwarming'],
  },
  {
    id: '10',
    title: 'Pulp Fiction',
    posterUrl: 'https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
    year: 1994,
    isFeatured: true,
    genre: 'Crime, Drama',
    quality: 'HD',
    tags: ['Featured', 'Iconic'],
  },
];

export const initialLatestReleases: Movie[] = [
  {
    id: '11',
    title: 'Oppenheimer',
    posterUrl: 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    year: 2023,
    isFeatured: false,
    genre: 'Biography, Drama, History',
    quality: '4K',
    tags: ['New Release'],
  },
  {
    id: '12',
    title: 'Barbie',
    posterUrl: 'https://image.tmdb.org/t/p/w500/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg',
    year: 2023,
    isFeatured: false,
    genre: 'Comedy, Adventure, Fantasy',
    quality: 'HD',
    tags: ['New Release'],
  },
  {
    id: '13',
    title: 'Everything Everywhere All at Once',
    posterUrl: 'https://image.tmdb.org/t/p/w500/w3LxiVYUpllpCmst2stCDsqeRJt.jpg',
    year: 2022,
    isFeatured: false,
    genre: 'Action, Adventure, Sci-Fi',
    quality: '4K',
    tags: ['New Release'],
  },
  {
    id: '14',
    title: 'The Batman',
    posterUrl: 'https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg',
    year: 2022,
    isFeatured: false,
    genre: 'Action, Crime, Drama',
    quality: 'HD',
    tags: ['New Release'],
  },
  {
    id: '15',
    title: 'Top Gun: Maverick',
    posterUrl: 'https://image.tmdb.org/t/p/w500/62HCnUTziyWcpDaBO2i1DX17ljH.jpg',
    year: 2022,
    isFeatured: false,
    genre: 'Action, Drama',
    quality: '4K',
    tags: ['New Release'],
  },
  {
    id: '16',
    title: 'Avatar: The Way of Water',
    posterUrl: 'https://image.tmdb.org/t/p/w500/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg',
    year: 2022,
    isFeatured: false,
    genre: 'Sci-Fi, Adventure, Action',
    quality: 'HD',
    tags: ['New Release'],
  },
   {
    id: '17',
    title: 'Knives Out',
    posterUrl: 'https://image.tmdb.org/t/p/w500/pThyQovXQrw2m0s9x82twY4mrJg.jpg',
    year: 2019,
    isFeatured: false,
    genre: 'Comedy, Crime, Mystery',
    quality: 'HD',
    tags: ['Popular'],
  },
  {
    id: '18',
    title: 'Get Out',
    posterUrl: 'https://image.tmdb.org/t/p/w500/kLuEtcQ9w0iGl2dACcs2eFPq0T5.jpg',
    year: 2017,
    isFeatured: false,
    genre: 'Horror, Mystery, Thriller',
    quality: '4K',
    tags: ['Critically Acclaimed'],
  },
  {
    id: '19',
    title: 'Mad Max: Fury Road',
    posterUrl: 'https://image.tmdb.org/t/p/w500/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg',
    year: 2015,
    isFeatured: false,
    genre: 'Action, Adventure, Sci-Fi',
    quality: 'HD',
    tags: ['Adrenaline Rush'],
  },
  {
    id: '20',
    title: 'The Social Network',
    posterUrl: 'https://image.tmdb.org/t/p/w500/n0ybibhJtQ5icDqNs2BTjpSFbOk.jpg',
    year: 2010,
    isFeatured: false,
    genre: 'Drama, History',
    quality: '4K',
    tags: ['Biography'],
  },
  {
    id: '21',
    title: 'Whiplash',
    posterUrl: 'https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg',
    year: 2014,
    isFeatured: false,
    genre: 'Drama, Music',
    quality: 'HD',
    tags: ['Intense'],
  },
  {
    id: '22',
    title: 'Blade Runner 2049',
    posterUrl: 'https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg',
    year: 2017,
    isFeatured: false,
    genre: 'Sci-Fi, Thriller',
    quality: '4K',
    tags: ['Visually Stunning'],
  },
  {
    id: '23',
    title: 'La La Land',
    posterUrl: 'https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdEjzEVX5d6CeJo.jpg',
    year: 2016,
    isFeatured: false,
    genre: 'Comedy, Drama, Music',
    quality: 'HD',
    tags: ['Musical'],
  },
  {
    id: '24',
    title: 'A Quiet Place',
    posterUrl: 'https://image.tmdb.org/t/p/w500/nAU74GmpUk7t5iklEp3bufwDq4n.jpg',
    year: 2018,
    isFeatured: false,
    genre: 'Horror, Sci-Fi',
    quality: '4K',
    tags: ['Suspenseful'],
  },
  {
    id: '25',
    title: 'The Grand Budapest Hotel',
    posterUrl: 'https://image.tmdb.org/t/p/w500/eWdyYQreja6JGCzqHWXpWHDrrPo.jpg',
    year: 2014,
    isFeatured: false,
    genre: 'Comedy, Drama',
    quality: 'HD',
    tags: ['Quirky'],
  },
  {
    id: '26',
    title: 'Arrival',
    posterUrl: 'https://image.tmdb.org/t/p/w500/x2FJsf1ElAgr63Y3PNPtJrcmpoe.jpg',
    year: 2016,
    isFeatured: false,
    genre: 'Drama, Sci-Fi',
    quality: '4K',
    tags: ['Thought-Provoking'],
  },
  {
    id: '27',
    title: 'Her',
    posterUrl: 'https://image.tmdb.org/t/p/w500/eCOtqtf5sALt02v9i8uY0Sj32yT.jpg',
    year: 2013,
    isFeatured: false,
    genre: 'Romance, Sci-Fi, Drama',
    quality: 'HD',
    tags: ['Futuristic'],
  },
  {
    id: '28',
    title: 'Moonlight',
    posterUrl: 'https://image.tmdb.org/t/p/w500/490v25cK4A4v4KdcK2c7a33a2s.jpg',
    year: 2016,
    isFeatured: false,
    genre: 'Drama',
    quality: '4K',
    tags: ['Oscar Winner'],
  },
  {
    id: '29',
    title: 'Jojo Rabbit',
    posterUrl: 'https://image.tmdb.org/t/p/w500/7GsM4fCHb3Y2F7eP2xxlK22r5W3.jpg',
    year: 2019,
    isFeatured: false,
    genre: 'Comedy, Drama, War',
    quality: 'HD',
    tags: ['Satire'],
  },
  {
    id: '30',
    title: '1917',
    posterUrl: 'https://image.tmdb.org/t/p/w500/iZf0KyrE25z1sage4SYFLCCrMi9.jpg',
    year: 2019,
    isFeatured: false,
    genre: 'War, Drama',
    quality: '4K',
    tags: ['One-Shot'],
  },
  {
    id: '31',
    title: 'The Revenant',
    posterUrl: 'https://image.tmdb.org/t/p/w500/ji4FvocS29E0GKS1UNUuQYm7yiu.jpg',
    year: 2015,
    isFeatured: false,
    genre: 'Western, Drama, Adventure',
    quality: 'HD',
    tags: ['Survival'],
  },
  {
    id: '32',
    title: 'Spider-Man: Into the Spider-Verse',
    posterUrl: 'https://image.tmdb.org/t/p/w500/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg',
    year: 2018,
    isFeatured: false,
    genre: 'Animation, Action, Adventure',
    quality: '4K',
    tags: ['Animated'],
  },
  {
    id: '33',
    title: 'Ford v Ferrari',
    posterUrl: 'https://image.tmdb.org/t/p/w500/6ApDtO7xaWAfPZfi2wAbjdsSzaX.jpg',
    year: 2019,
    isFeatured: false,
    genre: 'Action, Drama',
    quality: 'HD',
    tags: ['Racing'],
  },
  {
    id: '34',
    title: 'Logan',
    posterUrl: 'https://image.tmdb.org/t/p/w500/fnbjcRDYn6YviCcePDnGdyAkYsB.jpg',
    year: 2017,
    isFeatured: false,
    genre: 'Action, Drama, Sci-Fi',
    quality: '4K',
    tags: ['Gritty'],
  },
  {
    id: '35',
    title: 'Once Upon a Time in Hollywood',
    posterUrl: 'https://image.tmdb.org/t/p/w500/8j58iEBw9pYFD2L7lqRN4kdDy9e.jpg',
    year: 2019,
    isFeatured: false,
    genre: 'Comedy, Drama',
    quality: 'HD',
    tags: ['Tarantino'],
  },
  {
    id: '36',
    title: 'Soul',
    posterUrl: 'https://image.tmdb.org/t/p/w500/hm58Jw4Lw8I58gUvbwPIup1RTRh.jpg',
    year: 2020,
    isFeatured: false,
    genre: 'Animation, Comedy, Drama',
    quality: '4K',
    tags: ['Pixar'],
  },
];

    